// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using inzynierka.Data;

#nullable disable

namespace inzynierka.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandOwner")
                        .HasColumnType("text");

                    b.Property<string>("Brands")
                        .HasColumnType("text");

                    b.Property<double?>("Carbohydrates100g")
                        .HasColumnType("double precision");

                    b.Property<string>("Categories")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Countries")
                        .HasColumnType("text");

                    b.Property<string>("CountriesCode")
                        .HasColumnType("text");

                    b.Property<string>("EcoScoreGrade")
                        .HasColumnType("text");

                    b.Property<double?>("Energy100g")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergyKcal100g")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergyKcalServing")
                        .HasColumnType("double precision");

                    b.Property<double?>("Fat100g")
                        .HasColumnType("double precision");

                    b.Property<double?>("Fiber100g")
                        .HasColumnType("double precision");

                    b.Property<string>("IngredientsText")
                        .HasColumnType("text");

                    b.Property<string>("IsVegan")
                        .HasColumnType("text");

                    b.Property<string>("IsVegetarian")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NovaGroup")
                        .HasColumnType("integer");

                    b.Property<string>("NutritionGrade")
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<double?>("Proteins100g")
                        .HasColumnType("double precision");

                    b.Property<double?>("Salt100g")
                        .HasColumnType("double precision");

                    b.Property<double?>("SaturatedFat100g")
                        .HasColumnType("double precision");

                    b.Property<string>("ServingSize")
                        .HasColumnType("text");

                    b.Property<double?>("Sodium100g")
                        .HasColumnType("double precision");

                    b.Property<double?>("Sugars100g")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Tag.AllergenTag.AllergenTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AllergenTags");
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Tag.AllergenTag.ProductAllergenTag", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("AllergenTagId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "AllergenTagId");

                    b.HasIndex("AllergenTagId");

                    b.ToTable("ProductAllergenTag");
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Tag.CategoryTag.CategoryTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CategoryTags");
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Tag.CategoryTag.ProductCategoryTag", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryTagId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "CategoryTagId");

                    b.HasIndex("CategoryTagId");

                    b.ToTable("ProductCategoryTag");
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Tag.CountryTag.CountryTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CountryTags");
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Tag.CountryTag.ProductCountryTag", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("CountryTagId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "CountryTagId");

                    b.HasIndex("CountryTagId");

                    b.ToTable("ProductCountryTag");
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Tag.IngredientTag.IngredientTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IngredientTags");
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Tag.IngredientTag.ProductIngredientTag", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientTagId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "IngredientTagId");

                    b.HasIndex("IngredientTagId");

                    b.ToTable("ProductIngredientTag");
                });

            modelBuilder.Entity("inzynierka.API.Shared.Model.UserProduct", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("UserProduct");
                });

            modelBuilder.Entity("inzynierka.API.User.Model.TokenInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("TokenInfos");
                });

            modelBuilder.Entity("inzynierka.API.User.Model.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("inzynierka.API.User.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("inzynierka.API.User.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("inzynierka.API.User.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("inzynierka.API.User.Model.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Tag.AllergenTag.ProductAllergenTag", b =>
                {
                    b.HasOne("inzynierka.API.Product.Model.Tag.AllergenTag.AllergenTag", "AllergenTag")
                        .WithMany("ProductAllergenTags")
                        .HasForeignKey("AllergenTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("inzynierka.API.Product.Model.Product", "Product")
                        .WithMany("ProductAllergenTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllergenTag");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Tag.CategoryTag.ProductCategoryTag", b =>
                {
                    b.HasOne("inzynierka.API.Product.Model.Tag.CategoryTag.CategoryTag", "CategoryTag")
                        .WithMany("ProductCategoryTags")
                        .HasForeignKey("CategoryTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("inzynierka.API.Product.Model.Product", "Product")
                        .WithMany("ProductCategoryTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryTag");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Tag.CountryTag.ProductCountryTag", b =>
                {
                    b.HasOne("inzynierka.API.Product.Model.Tag.CountryTag.CountryTag", "CountryTag")
                        .WithMany("ProductCountryTags")
                        .HasForeignKey("CountryTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("inzynierka.API.Product.Model.Product", "Product")
                        .WithMany("ProductCountryTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountryTag");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Tag.IngredientTag.ProductIngredientTag", b =>
                {
                    b.HasOne("inzynierka.API.Product.Model.Tag.IngredientTag.IngredientTag", "IngredientTag")
                        .WithMany("ProductIngredientTags")
                        .HasForeignKey("IngredientTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("inzynierka.API.Product.Model.Product", "Product")
                        .WithMany("ProductIngredientTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientTag");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("inzynierka.API.Shared.Model.UserProduct", b =>
                {
                    b.HasOne("inzynierka.API.Product.Model.Product", "Product")
                        .WithMany("UserProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("inzynierka.API.User.Model.User", "User")
                        .WithMany("UserProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Product", b =>
                {
                    b.Navigation("ProductAllergenTags");

                    b.Navigation("ProductCategoryTags");

                    b.Navigation("ProductCountryTags");

                    b.Navigation("ProductIngredientTags");

                    b.Navigation("UserProducts");
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Tag.AllergenTag.AllergenTag", b =>
                {
                    b.Navigation("ProductAllergenTags");
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Tag.CategoryTag.CategoryTag", b =>
                {
                    b.Navigation("ProductCategoryTags");
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Tag.CountryTag.CountryTag", b =>
                {
                    b.Navigation("ProductCountryTags");
                });

            modelBuilder.Entity("inzynierka.API.Product.Model.Tag.IngredientTag.IngredientTag", b =>
                {
                    b.Navigation("ProductIngredientTags");
                });

            modelBuilder.Entity("inzynierka.API.User.Model.User", b =>
                {
                    b.Navigation("UserProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
